apiVersion: v1
kind: Pod
metadata:
  name: invalid-volume-pod
spec:
  containers:
  - name: main-container
    image: nginx:latest
    volumeMounts:
    - mountPath: /data
      name: missing-volume # Volume not defined
