apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: invalid-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: some-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: invalid-metric # Invalid resource metric
      target:
        type: Utilization
        averageUtilization: 50
