apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invalid-ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: non-existent-service # Service does not exist
            port:
              number: 80
