apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: invalid-crd.example.com
spec:
  group: example.com
  names:
    kind: InvalidCRD
    plural: invalidcrds
    singular: invalidcrd
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: string # Invalid schema (should be an object)
