apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: invalid-networkpolicy
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          non-existent-label: value # No matching namespace
