apiVersion: batch/v1
kind: CronJob
metadata:
  name: invalid-cronjob
spec:
  schedule: "invalid-schedule" # Invalid cron expression
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main-container
            image: nginx:latest
          restartPolicy: OnFailure
