apiVersion: v1
kind: Service
metadata:
  name: degraded-app-service
spec:
  selector:
    app: non-existent-selector # Selector mismatch to cause Service issues
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
