apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: degraded-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: non-existent-storage-class # Invalid storage class
